catalogMode: prefer
ignoreWorkspaceRootCheck: true
shellEmulator: true

trustPolicy: no-downgrade

catalogs:
  cli:
    '@antfu/eslint-config': ^6.6.1
    '@antfu/ni': ^28.0.0
    '@vitejs/plugin-vue': ^5.2.1
    '@vue-macros/volar': ^0.30.10
    '@vue/test-utils': ^2.4.6
    bumpp: ^10.3.2
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    publint: ^0.3.16
    simple-git-hooks: ^2.13.1
    tsx: ^4.21.0
    typescript: ^5.9.3
    vite: ^7.2.7
    vite-plugin-electron: ^0.29.0
    vite-plugin-electron-renderer: ^0.14.6
    vite-ssg: ^25.0.0
    vite-ssg-sitemap: ^0.8.1
  electron:
    '@electron/rebuild': ^4.0.1
    electron: ^34.2.0
    electron-builder: ^26.0.12
    electron-log: ^5.4.3
    electron-updater: ^6.6.2
  inlined:
    '@antfu/utils': ^9.3.0
  testing:
    jsdom: ^26.0.0
    tinyexec: ^1.0.2
    vitest: ^4.0.15
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.2
  types:
    '@types/node': ^25.0.1
  unocss:
    '@unocss/eslint-config': ^65.4.0
    '@unocss/eslint-plugin': ^65.4.0
    '@unocss/reset': ^65.4.0
    unocss: ^65.4.3
  unplugin:
    '@intlify/unplugin-vue-i18n': ^6.0.3
    unplugin-auto-import: ^19.0.0
    unplugin-vue-components: ^28.0.0
    unplugin-vue-macros: ^2.13.8
    unplugin-vue-router: ^0.10.9
  vue:
    '@vueuse/core': ^12.4.0
    '@vueuse/electron': ^12.7.0
    vue: ^3.5.13
    vue-i18n: ^11.1.1
    vue-router: ^4.5.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
